### PR TITLE
Stable upgraded to intermine 1.4

### PR DESCRIPTION
**Pull request by sergiocontrino**
i open the pull request for you to check. i have done a small build (only aig-gff) and webapp as test.
we could have a separate branch if preferred.
before merging i would create a tag (or release) of the current stable.
if i don't read from you i'll proceed (with the merging)  tomorrow.

### CODE REVIEW

**Comment by vivekkrish** [comment]
Hi @sergiocontrino, thank you for this pull request!

@eriksf will be bringing this up at our weekly meeting here at JCVI on Wednesday, to decide on the plan of action, since we have yet to deploy the minor ThaleMine 1.2.1 release. As such, I would like to request you to please hold off on the merging until then. Thanks!

**Comment by sergiocontrino** [comment]
ok @vivekkrish , perfect. i'll do one more test build in the meantime, and i'll wait for a green light from jcvi.

**Comment by vivekkrish** [comment]
Hi @sergiocontrino, we went ahead and merged all your changes into our stable.

It seems that you have a few more changes at your end which are in the `stable-1.4news` and `stable-1.4generif` branches. Whenever those are ready, they can be merged into this stable with subsequent pull requests.

**Comment by vivekkrish** [comment]
Also, there are 2 more commits we had to make after-the-fact of this merge, since they were somehow lost during the merge process (OAuth2 related and Panther loading related). Please refer to the HEAD of the stable branch for new changes.

**Comment by sergiocontrino** [comment]
thank you @vivekkrish , i had a feel that some may have slipped through.. i hope it was quick to fix.

**Pull request merged**
